### ISSUE TITLE
文档中的简单例子跑不起来

### ISSUE THREAD

**Issue by ElfenSterben** [amisadmin/fastapi-user-auth#35]
这个例子跑不起来, 我用 pip 安装的 
```from fastapi import FastAPI
from fastapi_amis_admin.admin.settings import Settings
from fastapi_user_auth.site import AuthAdminSite
from starlette.requests import Request
from sqlmodel import SQLModel

# 创建FastAPI应用
app = FastAPI()

# 创建AdminSite实例
site = AuthAdminSite(settings=Settings(database_url='sqlite:///amisadmin.db?check_same_thread=False'))
auth = site.auth
# 挂载后台管理系统
site.mount_app(app)


# 创建初始化数据库表
@app.on_event("startup")
async def startup():
    await site.db.async_run_sync(SQLModel.metadata.create_all, is_session=False)
        # 创建默认管理员,用户名: admin,密码: admin, 请及时修改密码!!!
    await auth.create_role_user("admin")
    # 创建默认超级管理员,用户名: root,密码: root, 请及时修改密码!!!
    await auth.create_role_user("root")
    # 运行site的startup方法,加载casbin策略等
    await site.router.startup()
    # 添加一条默认的casbin规则
    if not auth.enforcer.enforce("u:admin", site.unique_id, "page", "page"):
        await auth.enforcer.add_policy("u:admin", site.unique_id, "page", "page", "allow")


# 要求: 用户必须登录
@app.get("/auth/get_user")
@auth.requires()
def get_user(request: Request):
    return request.user


if __name__ == '__main__':
    import uvicorn

    uvicorn.run(app)```



```
C:\Users\es\projects\esdata-backend\test.py:18: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @app.on_event("startup")
INFO:     Started server process [14908]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\starlette\routing.py", line 705, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\starlette\routing.py", line 584, in __aenter__
    await self._router.startup()
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\starlette\routing.py", line 682, in startup
    await handler()
  File "C:\Users\es\projects\esdata-backend\test.py", line 26, in startup
    await site.router.startup()
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\starlette\routing.py", line 682, in startup
    await handler()
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\fastapi_user_auth\admin\admin.py", line 388, in _load_policy
    await self.load_policy()
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\fastapi_user_auth\admin\admin.py", line 391, in load_policy
    await self.site.auth.enforcer.load_policy()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\es\.pyenv\pyenv-win\versions\3.11.3\Lib\functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\fastapi_user_auth\auth\auth.py", line 92, in enforcer
    enforcer = AsyncEnforcer(
               ^^^^^^^^^^^^^^
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\casbin\core_enforcer.py", line 63, in __init__
    self.init_with_adapter(model, adapter)
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\casbin\core_enforcer.py", line 84, in init_with_adapter
    self.init_with_model_and_adapter(m, adapter)
  File "C:\Users\es\projects\esdata-backend\venv\Lib\site-packages\casbin\async_internal_enforcer.py", line 35, in init_with_model_and_adapter
    raise RuntimeError("Invalid parameters for enforcer.")
RuntimeError: Invalid parameters for enforcer.

ERROR:    Application startup failed. Exiting.

```

**Comment by ElfenSterben** [comment]
似乎是 casbin 的问题 这是 1.35 的 casbin/async_internal_enforcer.py 文件
![image](https://github.com/amisadmin/fastapi-user-auth/assets/19554131/34d2088a-2f82-4469-af40-82686d5003a7)
这是 casbin 1.33 的 casbin/async_internal_enforcer.py 文件
![image](https://github.com/amisadmin/fastapi-user-auth/assets/19554131/33faa3dd-2c09-46a1-8baf-ada110b1e69a)

**Comment by ElfenSterben** [comment]
Auth.enforcer 这个函数里 Adapter 用错了

![image](https://github.com/amisadmin/fastapi-user-auth/assets/19554131/22f8f890-b571-49a8-aef7-8ad8e2472c0b)

**Comment by amisadmin** [comment]
确保自己用的是最新版本
